name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: test for singleton
      run: cd singleton && go test -v 

    - name: test for prototype
      run: cd prototype && go test -v 

    - name: test for strategy
      run: cd strategy && go test -v 

    - name: test for simplefactory
      run: cd simplefactory && go test -v 

    - name: test for factory
      run: cd factory && go test -v 

    - name: test for abstract_factory
      run: cd abstract_factory && go test -v 

    - name: test for builder
      run: cd builder && go test -v 

    - name: test for proxy
      run: cd proxy && go test -v 

    - name: test for bridge
      run: cd bridge && go test -v 
    
    - name: test for decorator
      run: cd decorator && go test -v 
    
    - name: test for adapter
      run: cd adapter && go test -v 

    - name: test for facade
      run: cd facade && go test -v 

    - name: test for composite
      run: cd composite && go test -v 

    - name: test for flyweight
      run: cd flyweight && go test -v 

    - name: test for observer
      run: cd observer && go test -v 
