name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: test for singleton
      run: cd singleton && go test -v 

    - name: test for prototype
      run: cd prototype && go test -v 

    - name: test for strategy
      run: cd strategy && go test -v 

    - name: test for simplefactory
      run: cd simplefactory && go test -v 